### ISSUE TITLE
The loading doesn't show on material dashboard

### ISSUE THREAD

**Issue by hackerunet** [nezhar/snypy-frontend#35]
The loader failed to be displayed on material dashboard. Not sure why, I added all code in all parts of the application, I even get a loading output console on each request but the component never shows up, no errors or warnings or any other.

**Comment by mathalaichandar** [comment]
I am having the same issue as reported by hackerunet. I can see console log for startloading() and stoploading() but loadingStatus seems to be not changing, any idea why

**Comment by nezhar** [comment]
I also experienced this in a project, and it appears to be related on event handling because the loading variable holds the right value in the ts code but in the template it is not updated.

The best solution I found is to control the loading screen display using the `ngAfterViewInit`:

```
  constructor(private loadingScreenService: LoadingScreenService,
              private _elmRef: ElementRef,
              private _changeDetectorRef: ChangeDetectorRef) {
  }

  ngAfterViewInit(): void {
    this._elmRef.nativeElement.style.display = 'none';
    this.loadingSubscription = this.loadingScreenService.loadingStatus.pipe(debounceTime(this.debounceTime)).subscribe(
      (status: boolean) => {
        this._elmRef.nativeElement.style.display = status ? 'block' : 'none';
        this._changeDetectorRef.detectChanges();
      }
    );
  }
```

You can see all changes in this commit: https://github.com/nezhar/snypy-frontend/commit/7e17a8dad216e556c084593a569f9debb1b66a61
